services:
  app:
    working_dir: '/app'
    image: 'node:18-alpine'
    ports:
      - '3000:3000'
      - '9229:9229'
    restart: unless-stopped
    volumes:
      - '.:/app'
    command: sh -c 'npm install && npm run dev'