name: Dev Workflow - Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main

      - name: 'Install podman'
        uses: gacts/install-podman@v1.1.1

      - name: 'Read package.json'
        uses: rexdefuror/read-package-json@v1.0.5
        
      - name: 'Build Image'
        run: |
          podman build . -t ghcr.io/ptrk25/${{ github.event.repository.name }}:v${{ env.PACKAGE_VERSION }}
